### ISSUE TITLE
Selecting 

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/cu_campus_map_bundle#9]
Zoom doesn't work when a Location Marker is selected while Map Center is default and then Map Center is changed.  While the description of the Location Marker field says "The map center option must be set to default", it doesn't actually reset the value of the field when the Location Marker is changed.

**Comment by cathysnider** [comment]
I'm not seeing any error when Zooming, not when a Location Marker is selected nor any other time. It all works smoothly, both in production and on local.

Zooming In:
![Screen Shot 2020-01-28 at 11 59 52 AM](https://user-images.githubusercontent.com/638275/73296308-b2f5ba80-41c6-11ea-86ac-a3178e1d9b14.png)

Zooming Out:
![Screen Shot 2020-01-28 at 11 59 32 AM](https://user-images.githubusercontent.com/638275/73296434-f6e8bf80-41c6-11ea-8cba-6d0d8c95fa18.png)
